apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grocy
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grocy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grocy
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeName }}
      containers:
        - name: grocy
          image: linuxserver/grocy:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 80
          volumeMounts:
            - name: grocy-data
              mountPath: /var/www/data
            - name: tmp-dir
              mountPath: /tmp
            - name: viewcache
              mountPath: /var/www/data/viewcache
              mountPropagation: HostToContainer
              subPath: viewcache
              readOnly: false
            - name: scanner-device
              mountPath: {{ .Values.scannerDevicePath }}
              readOnly: true
    
      volumes:
        - name: grocy-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-grocy-pvc
        - name: tmp-dir
          emptyDir:
            medium: Memory
        - name: viewcache
          emptyDir:
            medium: Memory
        - name: scanner-device
          hostPath:
            path: {{ .Values.scannerDevicePath }}
            type: CharDevice
