apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grocy-pvc
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi  # Set appropriate storage size
  storageClassName: {{ .Values.storageClass }}
